### ISSUE TITLE
Detalle de traducción: intro.md

### ISSUE THREAD

**Issue by a-morelos** [Eloquent-JavaScript-Espanol/Eloquent-JavaScript-ES#2]
Hay un detalle de traducción en la `00_intro.md`: 

> La programación, resulta, es difícil[...]

Creo que podemos cambiarlo por:

> La programación, en realidad, es difícil

**Comment by hectorip** [comment]
Me gusta, lo cambiamos.

**Comment by hectorip** [comment]
Lo cierro.
